### ISSUE TITLE
some questions of implementation details

### ISSUE THREAD

**Issue by wwjwhen** [JianshuZhang/WAP#3]
Hi, jianshu, I have went through the whole project of Dense+WAP, I have two debuts:
First, you are using $U_a convoluted with a_i $ in your codes instead of dot product in your article, is this an empirical trick?
Second, 
![image](https://user-images.githubusercontent.com/7140791/37891961-cc4db8be-3108-11e8-8beb-d8b8b5851d93.png) in these two lines, the first line can already produce the result as shown in your article, yet you are still using mask to combine $h_2$ and $h_1$, is there any theory about this operation?
Looking forward to your reply!Thanks!

**Comment by JianshuZhang** [comment]
1. There is no difference between 1x1 convolution and dot product. I chose 1x1 convolution instead of dot product to avoid some reshape operation, saving some run time.
2. When you train your model with several samples in one batch, the length of output Y of each sample differs in one batch. So, a mask operation on the decoder state is needed.

**Comment by wwjwhen** [comment]
Thanks for your prompt reply, so you mean that in the second line  h1 is used to pad the decoder state?

**Comment by JianshuZhang** [comment]
Yes. If m_ is 0, then h1 represents previous decoder state.

**Comment by wwjwhen** [comment]
OK, got it, thanks a lot!
